---
title: "2015 November Meeting"
date: 2015-11-09
type: post
layout: post
tags: blog
status: published
author: 4
when: 2015-11-10 11:30
location: prototek
topic: "Docker for Java Developers"
---

Producing good software is a goal many of us strive for by honing our
skills at design principles,
language mastery,
architecture, methodologies, and expert use of libraries, frameworks,
and platforms.  Satisfied with our code, we then figure out how to
deploy it, or we hand it over to an operations team who handles running
it in production. Running software in production is the whole point!
 We can apply a lot of our skills and practices from software
development to its deployment, and to the infrastructure on which it
runs. https://www.docker.com/what-docker[Docker] is "an open platform
for distributed applications for developers and sysadmins" that provides
a standardized way to package applications with the specification of
their environment.  This means everything from the operating system to
the application server is specified in code, and will be identical
between your environments.

== Speaker Bio
Kenyatta Clark


== Pizza, Chairs, etc.

We thank http://techlahoma.org/[Techlahoma] for generously
providing the materials for the meeting, including the projector,
pizza, and chairs.
