---
title: "August 2008"
date: 2008-08-12
type: post
layout: post
tags: blog
status: published
author: 1
---

== Lunch Meeting (link:/index.php?option=com_attend_events&task=view&id=21[register here]) +

When:August 12, 2008 11:30-12:40

Where: University of Phoenix room *308 * (see
link:/component/option,%20%3Ca%20href=[order] com_google_maps/Itemid,
31/" title="Meeting
location">Meeting location or http://tinyurl.com/6xz439[here] )

* Topic: JSF2 Component Development in a 1.2 World +

Speaker: link:/content/view/57/34/[Jason Lee] +

Sponsor: GDH +

*Agenda*

* 11:30 am - Welcome Announcements

* 11:40 am - Main Presentation
* 12:40 pm - Wrap Up

== Evening Meeting (link:/index.php?option=com_attend_events&task=view&id=22[register here]) +

When: August 12, 2008 6:00PM

Where: University of Phoenix room ??? (see
link:/component/option,com_google_maps/Itemid,31/[Meeting location or]
http://tinyurl.com/6xz439[here] )

* Topic: JSF2 Component Development in a 1.2 World

Speaker: link:/content/view/57/34/[Jason Lee]

Food and drinks will *not* be provided! +

*Agenda*

* 5:30 pm - Eat, chat, network time +
* 6:00 pm - Welcome Announcements
* 6:05 pm - Presentation
* 7:30 pm - Open the floor to questions, discussion, network time

== Presentation Information

One of the improvements coming in JSF 2 is the vast simplification of
component development, but JSF 2 is months away, and you want that
functionality NOW, so what's an impatient developer to do?

Enter JSFTemplating and JSF Extensions. Using these two libraries, it is
possible to use an approach very similar to what JSF 2 will offer, but
can be done using JSF 1.2. In this presentation, we'll peek under the
hood of Mojarra Scales, a component set that uses this approach, and see
what it has to offer.

"
