---
title: About
layout: post
permalink: /about.html
---

== Our Mission
* - To Spread the News of Java.
* - To Enable Developers with Knowledge, Information and Tools.
* - To Expose Members to All Aspects of the Java Universe in a fun, non-threatening environment.
* - This group is FREE to join, and is aimed at promoting Java and related
topics to the greater Oklahoma City area.

== Our Leadership
The leadership of the JUG is very populist, having a Steering Committee
that meets once a month to plan the various JUG events, as well as
making long term decisions for the JUG. These meetings are open to
everyone, with the membership of the Steering Committee being loosely
defined as those who consistently attend the meetings. We do, however,
have a basic structure to which we assign the ultimate responsibility of
ensuring the functions and decisions of the Steering Committee are
carried out. This very small structure consists of a president and
treasurer. Currently, those posts are held by:

* - President: Jason Lee
* - Vice President: _open_