---
title: "May 2009"
date: 2009-09-10
type: post
layout: post
tags: blog
status: published
author: 1
---

== Lunch Meeting (link:/index.php?option=com_attend_events&task=view&id=34[register here] ) +

When: May 12, 11:30-12:40

Where: Oklahoma City Coworking Collaborative** ** (see
http://okccoco.com/?page_id=109[Meeting location] )

* Topic:  Beginning JavaScript for Java Developers

Speaker: link:/content/view/57/34/[Jason Lee] +

*Agenda*

* 11:30 am - Welcome Announcements

* 11:40 am - Main Presentation
* 12:40 pm - Wrap Up

== Presentation Information +

These days, writing
Java-based web apps require more than just Java.  With user interactions
becoming richer and more dynamic,
one language that every web developer should know is JavaScript.  In
this session, we'll take a look some of the basic concepts of JavaScript
-- including variable scopes,classes, closures, and testing -- that will
be helpful for a Java developer who is starting to learn this powerful
and popular language.

"
