---
title: "Job Opportunity with CompSource Oklahoma"
date: 2013-08-13
type: post
layout: post
tags: blog
status: published
author: 4
---

CompSource Oklahoma is seeking a self-motivated and enthusiastic Java developer
to join our team.  This role will be part of a project to convert our
legacy enterprise system to an off-the-Shelf, Web-based/J2EE system."
Location: Oklahoma City Salary: $50,000 - $72,000"

As a member of the conversion team, this position will work closely with our vendors,
stakeholders, business analysts, developers and other team members to
configure and customize the application in support of key business
initiatives.

== Education and Experience Requirements

* Minimum of two (2) years Java programming experience
* Bachelor's degree in Computer Science preferred
* Experience with working with Guidewire Insurance suite and PL/SQL is a plus.

== Skills and Abilities

* To understand, articulate, and conform to core OOP principles.
* To understand, utilize, and leverage core Java architecture.
* Demonstrated ability to voice ideas and expertise during development
process and concisely translate the requirements into program specifications.
* Excellent problem solving skills and troubleshooting skills.
* Excellent written and verbal communication skills as well as the
ability to work well with a wide variety of people with varying
technical skill sets and business knowledge.

Excellent benefit package includes paid vacation, sick leave, paid
holidays and health, dental and life insurance.  *EEO/AA Employer.*
Please submit cover letter and resume to Christy_M@compsourceok.com
