---
title: "2017 January Meeting"
date: 2017-01-05
type: post
layout: post
tags: blog
status: published
author: 8
when: 2017-01-10 11:30
location: starspace
topic: "gRPC 101 for Java Developers"

---

gRPC is a high performance, open source, general RPC framework that puts
mobile and HTTP/2 first. gRPC is based on many years of Google's
experience in building distributed systems - it is designed to be low
latency, bandwidth and CPU efficient, to create massively distributed
systems that span data centers, as well as power mobile apps, real-time
communications, IoT devices and APIs. It's also interoperable between
multiple languages.

But beyond that fact that it's more efficient than REST, we'll look into
how to use gRPC's streaming API, where you can establish server-side
streaming, client-side streaming, and bidirectional streaming! This
allows developers to build sophisticated real-time applications with
ease.

In addition to learning about gRPC and HTTP/2 concepts with code and
demonstrations, we'll also deep dive into integration with existing
build systems such as Maven and Gradle, but also frameworks such as
Spring Boot and RxJava.

* Writing/using a Spring Boot starter to run gRPC server
* Configuring projects to generate gRPC stub code
* Integrating w/RxJava's observable sequences, which matches very well
with gRPC's Stream Observable constructs

== Speaker Bio:

Ray Tsang is a Developer Advocate for the Google Cloud Platform. Ray had
extensive hands on cross-industry enterprise systems integration
delivery and management experiences during his time at Accenture,
managed full stack application development, DevOps, and ITOps. Ray
specialized in middleware, big data, and PaaS products during his time
at Red Hat while contributing to open source projects, such as
Infinispan. Aside from technology, Ray enjoys traveling and adventures.

Please go to Meetup and sign up so we will have a count for the food.
http://meetu.ps/e/CjXlj/hQ4T0/d[Meetup] We thank
http://techlahoma.org/[Techlahoma] for generously providing the food
and drink, and to http://www.starspace46.com/[StarSpace46] for providing
the facility.
